### PR TITLE
Russian language support added

### PR DESCRIPTION
**Pull request by rufanov**

### CODE REVIEW

**Comment by VahidN** [comment]
Thanks. Are you sure `and` in Russian is equal to` و`?

**Comment by rufanov** [comment]
> Thanks. Are you sure `and` in Russian is equal to` و`?

Nope, it was mistake from copy-pasting Arabic. Fixed )

**Comment by rufanov** [comment]
Also found misspell in one word, so PR updated again to fix it

**Comment by VahidN** [comment]
Thanks.

**Pull request merged**
